### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [asingh1969/tc359-project7#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by chrisvfritz** [comment]
Any luck on this yet? Let me know if you're stuck and I'll be happy to help.

**Comment by asingh1969** [comment]
Yeah I updated the showcase but I since the heroku url didn't change I guess you wouldn't be able to see the change, my bad. But yes I updated the project, the url is https://vast-peak-2670.herokuapp.com/

**Comment by chrisvfritz** [comment]
:+1: Much better! Great work. :smiley:
